### ISSUE TITLE
Mine OS crashes when i create a server

### ISSUE THREAD

**Issue by davewanders** [hexparrot/mineos-node#149] opened 2015-11-22 20:47 UTC
Error log: http://pastebin.com/kvMeP8a4
git commit: 036abe2

**Comment by hexparrot** [comment] 2015-11-22 21:32
This might be caused by an old `node` version.  You appear to have 0.10.x, while the stable 4.x has already been released (and is what all testing is done on).

As best as I can tell, the error "Error: Cannot find module 'bytes'" should be resolved with a newer version.

So you can try the following things first:

    npm cache clean
    npm install

And try it again.  If it doesn't work, 4.x might be the next best thing to do (actually going to 4.x+ is probably the best thing anyway).

**Comment by hexparrot** [comment] 2015-11-24 16:25
#150

**Closed** 2015-11-26 16:52 UTC
Labels: bug

**Comment by hexparrot** [comment] 2015-11-26 19:40
What did you do that fixed it?
