### ISSUE TITLE
Connection Refused - Supervisor Uptime = 12 seconds before restart.

### ISSUE THREAD

**Issue by Mortalife** [hexparrot/mineos-node#105] opened 2015-09-05 18:45 UTC
Hello,

I have recently install MineOS-Node from the Turnkey ISO you made available. I was having some issues with the dashboard where socket.io was not communicating successfully. I decided to update the webui files via git and have since been unable to connect to the server. I receive a connection refused message.

![image](https://cloud.githubusercontent.com/assets/14141518/9700745/9b396656-5406-11e5-9d5d-ef69e2edc3d2.png)

When it does accept the main html request, subsequent requests are refused.
![errors](https://cloud.githubusercontent.com/assets/14141518/9700738/60f044ba-5406-11e5-9b1a-57e83bbf3b5f.png)

Supervisor shows it restarting every 12 seconds, I have attempted to view the logs but nothing of significance is apparent. Is the Master branch currently stable?

![image](https://cloud.githubusercontent.com/assets/14141518/9700742/8d4cea9a-5406-11e5-865c-c391369b9251.png)

**Comment by Mortalife** [comment] 2015-09-05 19:55
Okay, so I've investigated this further. I've removed all mineos files and logs, and reinstalled. Removed all servers from the server folder and it starts fine. If I attempt to import a server it creates the server fine, but it does not recognise the .jar's in the folder and from that moment on it restarts every 10 seconds.

**Comment by hexparrot** [comment] 2015-09-05 20:52
Alright, thanks for the detail! Hopefully we can get this figured out!

For starters, master should definitely always be in a working state.  It's the preferred place for everybody to update to.  However, because of the use of NPM for dependencies, you must also remember `npm install` (in addition to pulling the most recent git commit), to ensure that all components MineOS is expecting are present.

So:

    cd /usr/games/minecraft
    git fetch
    git reset --hard origin/master
    npm install
(then restart the webui)

I haven't yet run into the issue you're experiencing, but this isn't the first time I've heard about it.  I would love to be able to reproduce it, as I'm sure it will give me more than enough to track it down and squash the bug.

I still can't tell if it's localized to certain installs, or if it's even a certain server.  I detected a bug today that might be related--it seems that `.zip` files do not properly get `chown`ed to the non-root user.  This could very well be the cause of the issue you're having; I've been working on this bug today and I hope to get it fixed very soon.

Last but not least, while I have serious suspicions it is *not* about the server imported itself, I always welcome getting a copy of the archive you try to import, so I may test it against real-world archives created for this purpose.  I'll continue to look into this and reproduce your issue and come up with a fix.

**Comment by Mortalife** [comment] 2015-09-05 21:09
Thanks for your reply. 

I have already completely reset the gui install as part of my fault finding, and yes I removed the provided modules folder and recreated it with npm install. 

Since posting this bug I have got it running, with a little wrangling. 
I created a new server from scratch then imported the profile for the Minecraft version my mod pack uses.
I then unzipped the file using the mc user into the created folder, overwriting any conflicting files. 
Then I refreshed my browser, and I could see my server but I couldn't select a .jar as the list wasn't populated. A couple of refreshes got me the option to select the required .jar file. I then was able to start the server.

This supports your import permissions theory.

**Comment by hexparrot** [comment] 2015-09-05 22:12
I just made a few commits which I believe should fix the issue we're experiencing.  Or at least, it should appropriately make sure all files are properly owned, which I'm hoping was the culprit to the issue you were experiencing.

I'd venture that you'd want to either 1) remove all your existing servers or 2) `chown -R` them manually.  Then upon updating `git` AND `npm install`, I hope that all file permissions from importing zip files should be a non-issue.

**Comment by mmonkey** [comment] 2015-09-13 18:41
I can recreate this problem another way:

1. Create a fresh MineOS-node environment (I'm running it on Debian Jessie)
2. Login to MineOS and create a new server (No jar selected)
3. FTP to that server and dump a preconfigured forge server.
4. Connection Refused in MineOS, `systemctl status mineos` shows new PID process every 30ish seconds.

5. Delete server folder from SSH or FTP, can access MineOS again.

I have the latest (9-13-15) version of MineOS-node and ran `npm install`

**Comment by hexparrot** [comment] 2015-09-13 19:30
I think the key here then is what happened in step 3, with your preconfigured server!

Do you think you can provide that to me so I may reproduce this issue and figure out this once and for all?

**Comment by mmonkey** [comment] 2015-09-13 22:06
Here is a [dropbox](https://www.dropbox.com/s/95fg1dn5x5unrmk/mc-backup.zip?dl=0) link containing a zipped version of what I transferred to the server.

Basically I just dropped the contents of this zip file directly into the MineOS-node server's directory. At that point MineOS becomes unreachable.

**Comment by hexparrot** [comment] 2015-09-21 21:56
I haven't been able to reproduce this issue, either with the most recent commit, or the last commit from 9/13 (db8834ce5fc669de61c1e5247ae9e6265c3fb3bd).  In the future, let me know the specific commit you're on, as that will help me be certain we're on the same version.  You can see the version from the webui, upon clicking your name at the top-right corner.

That said, I had assumed that you were using the 'import' functionality (putting the zip file in /imports/ and then using the webui), and that method worked to import the server (no crashes occurred yet).

But I also tried logging into SSH, unzipping that folder in the right place, and that also worked too.

I finally went and created a server and then SFTPed into the server, and dropped the unzipped contents directly into /var/games/minecraft/servers/test (the example server I made) and here I saw an error pop up: it was an attempt to get the filesize of a file that had not fully copied over.

HOWEVER.  I didn't experience any crash.  It just gave me a slight warning and a wrong value in the server status page, which was fixed by refreshing my browser.

So for the most part, I am entirely unable to reproduce this issue.  A few things to consider then:

1) what commit are you on?  (and why haven't you updated yet!)
2) does your error log (/var/log/mineos.log) show ..anything?
3) are you able to import the server using the import functionality with success? (also would be valuable to know even if you don't update your scripts with git)

**Comment by mmonkey** [comment] 2015-09-22 01:29
On latest, this is working. I was on latest (at the time) when I first posted. I this can be marked resolved.

**Closed** 2015-09-22 02:51 UTC
Labels: bug
