### ISSUE TITLE
Issuing /restart in game doesn't actually restart the server

### ISSUE THREAD

**Issue by adracamas** [hexparrot/mineos-node#270] opened 2018-03-14 15:58 UTC
Is there a start.sh or something we need to give the server to make that happen?

**Comment by hexparrot** [comment] 2018-03-14 16:44
Correct.  MineOS starts all Minecraft instances by invoking the java jar directly in a screen session, which is something that the console itself would not know how to reproduce.

start.sh files typically just have "if you exited, restart it" loops, which are simple and straightforward, but also sometimes really weird (because it makes closing the server contingent on killing the shell script or during forced pauses written into the script).

MineOS has functionality meant to mimic this, the function "restart", but it isn't heavily integrated into the UI because not every server will cleanly stop simply from 'stop' in console.  If you're using a server that does 100% of the time cleanly exit, you can use the restart functionality, either with `mineos_console.js` (`/.mineos_console.js -s myserver restart`) or by making a cronjob to do it. 

Otherwise, yes, there are too many varieties of 'restart' among the available server types and acceptable syntaxes that I couldn't make it a front-and-center feature.

**Comment by adracamas** [comment] 2018-03-16 02:10
Right on. Thank you for the clarification.
Cron jobs are based on a timer and can't exvaluate things like "server is down" can it? If I were to simply have it run the start server command, would it cause problems if the server is already running or will it simply just get ignored? (sorry,  I'm really unfamiliar with a lot of this. Take nothing I'm asking as negative, you have made a brilliant product)

**Comment by hexparrot** [comment] 2018-03-22 19:35
All attempts to start a server, whether from the webui or from `mineos_console.js` will do a check if the server is already up and running (again, provided it was invoked through MineOS in the first place).

That means yes, realistically you could have a cronjob constantly running that attempts to start the server and there will be no harm done.

Take a look at this post I made about how to use the 'verify' functionality in MineOS.  This has the added benefit of allowing you to actually check if it's up, rather than just attempt to start the server (and have the scripts abort).

https://discourse.codeemo.com/t/question-about-cron/2295/4?u=hexparrot

This gives you the additional flexibility of making any changes prior to starting the server which might be relevant for a started server (perhaps resetting inventories or changing a `server.properties` with sed, etc.).

**Closed** 2018-04-24 17:56 UTC
